### PR TITLE
WIP: report unexpected output involving non-ptr Error method

### PR DESCRIPTION
**Pull request by mvdan**
(see commit message)

### CODE REVIEW

**Comment by mvdan** [comment]
Also worth noting that I can't use `new(*errTargetNonPtr)`, as that will never match.

**Comment by frankban** [comment]
Interesting! `*errTargetNonPtr` still implements error, so when it is [formatted](https://github.com/frankban/quicktest/blob/master/format.go#L17) it matches the error case and therefore e<msg> is used, rather than the more generic `fmt.Sprintf("%# v", pretty.Formatter(v))`. We should probably more explicitly format "as" in the checker.

**Comment by mvdan** [comment]
Indeed; `as` is about the target type, not value, so IMO it should always print the type.

**Comment by mvdan** [comment]
Please feel free to take over the fix, by the way. I'm not familiar with the codebase, so it's not clear to me what bit of code should get fixed. Hopefully you can just reuse the test.

**Comment by frankban** [comment]
> Please feel free to take over the fix, by the way. I'm not familiar with the codebase, so it's not clear to me what bit of code should get fixed. Hopefully you can just reuse the test.

Sure, I proposed a possible fix at https://github.com/frankban/quicktest/pull/128

**Comment by mvdan** [comment]
Thanks! Closing in favor of that then.

**Pull request closed without merging**
