### PR TITLE
Return a more descriptive error message when Not is used with IsNil

### PR DESCRIPTION
**Pull request by frankban**
Fixes https://github.com/frankban/quicktest/issues/125

### CODE REVIEW

**Review by mvdan — COMMENTED** [review]
SGTM! Though I wonder if we should do the same for other "is" checkers where we could provide a helpful "is not" message to the user, such as ErrorsIs, Satisfies, Equals, Contains, etc. I actually think the majority, if not all, should have helpful "negative" messages.

**Comment by frankban** [comment]
Thanks for the review!
I agree that there is room for improving the negative messages for some other checkers. It would be nice to still have a good and sensible generic negative message as it is beneficial for all checker implementations that are not part of quicktest.

**Comment by mvdan** [comment]
Oh, for sure :)

**Review by rogpeppe — APPROVED** [review]
LGTM thanks.

**Comment by frankban** [comment]
Thanks for the reviews, filed https://github.com/frankban/quicktest/issues/129 for following up with other checkers.

**Pull request merged**
