### PR TITLE
Add syntax highlighting to the README code blocks

### PR DESCRIPTION
**Pull request by alireza-ahmadi**
I was browsing this repository and after reading the example and documentation on the README file, I thought reading these examples would've been easier if they had syntax highlighting. So, I added syntax highlighting to the `README.md` file.

I've edited files using the web editor so please let me know if you decided to merge this PR and I did mess something up in this commit.

### CODE REVIEW

**Comment by frankban** [comment]
This is a good idea. Unfortunately, we are using godocdown for generating the readme from the Go docs, as explained near the beginning of the file. It would be nice if godocdown would support generating md with code annotations.

**Comment by alireza-ahmadi** [comment]
👍
Makes sense. I'm closing this PR but, may take a look at it again when godocdown adds support for code annotation in the markdown files.

**Comment by frankban** [comment]
> may take a look at it again when godocdown adds support for code annotation in the markdown files.

That would be awesome, thanks!

**Comment by gilcrest** [comment]
Hi @frankban  - just wanted to jump in here as well - I hadn't heard of godocdown before - is [this](https://github.com/robertkrimen/godocdown) the repository for it? If so, it looks like it's pretty inactive and will likely not support this in the near future (it hasn't had a commit in 8 years?). 

I am of the opinion that code documentation is as important as the code itself. I think having syntax highlighting is helpful as well as other niceties you can get from a README. I'm willing to help with the README as well, if you'd reconsider not using a generated README? I do understand the tradeoffs that you're always keeping the doc in synch with the README using this method, so I understand it may not be worth it. FWIW, I have found the docs to be generally great and have been able to navigate to find what I need quite well, but it would be nice to have a Table of Contents, highlighting, etc. Thanks! Dan

**Comment by frankban** [comment]
Hey @gilcrest, those are very valid points. Indeed godocdown seems to no longer be maintained. We used to have in quicktest a very short README pointing users to the godoc website. godocdown gave us the ability to easily extend the readme to be more useful, without too much effort, and without having to maintain two sources of truth for the package docs. While really handy, the current approach also shows some limitations, some of them related to the resulting target, as  highlighted by @alireza-ahmadi, some of them related to the constraints of godoc, like lack of subheaders.
I just took a quick look at godocdown alternatives, there is a much more maintained library (https://github.com/posener/goreadme) that seems to support code highlighting, but lacks the templating features of godocdown.
So yes, it's all about tradeoffs. Probably quciktest is now mature enough that would be less difficult to maintain both godocs and markdown separately, so that we can use both at full potential?

**Comment by frankban** [comment]
I tried to capture this conversation at https://github.com/frankban/quicktest/issues/98

**Pull request closed without merging**
